name: flutter_base_project
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  get_it: ^3.0.3
  http: ^0.12.0+2
  rflutter_alert: ^1.0.2
  flutter_cache_manager: ^1.1.1
  rxdart: ^0.22.4
  json_annotation: ^3.0.0
  flushbar: ^1.9.1
#  connectivity: ^0.4.5



#  moor_flutter: ^2.0.0
#  path_provider: ^1.3.0
#  sqflite: ^1.1.7+1

  flutter_ui_control:
   path: E:/VrlocalProject/BaseProjects/flutter_ui_control

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  build_runner: ^1.7.1
  flutter_launcher_icons: ^0.7.3
#  flutter_stetho: ^0.5.0
#  moor_generator: ^2.0.1
#  built_value_generator: ^6.7.1

#  run command  flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/logo/ic_backgroud.png"
flutter_icons:
#    image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo/ic_launcher.png"
  image_path_ios: "assets/logo/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo/ic_backgroud.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo/ic_launcher.png" # only available for Android 8.0 devices and above

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
        - asset: assets/fonts/EBGaramond-Italic.ttf
          style: italic
        - asset: assets/fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/open_san/OpenSans-Regular.ttf
        - asset: assets/fonts/open_san/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_san/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_san/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family:  FontIcons
      fonts:
        - asset: assets/icons/FontIcons.ttf


  assets:
     - assets/logo/ic_launcher.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
